export const CREATE = 'users/CREATE'
export const FETCH = 'users/FETCH'
export const GET_OR_CREATE = 'users/GET_OR_CREATE'
export const HIDE = 'users/HIDE'
export const SETUP = 'users/SETUP'
export const UPDATE = 'users/UPDATE'

export const CREATE_ERROR = 'users/CREATE_ERROR'
export const FETCH_ERROR = 'users/FETCH_ERROR'
export const GET_OR_CREATE_ERROR = 'users/GET_OR_CREATE_ERROR'
export const HIDE_ERROR = 'users/HIDE_ERROR'
export const SETUP_SUCCESS = 'users/SETUP_SUCCESS'
export const UPDATE_ERROR = 'users/UPDATE_ERROR'

export const CREATE_SUCCESS = 'users/CREATE_SUCCESS'
export const FETCH_SUCCESS = 'users/FETCH_SUCCESS'
export const GET_OR_CREATE_SUCCESS = 'users/GET_OR_CREATE_SUCCESS'
export const HIDE_SUCCESS = 'users/HIDE_SUCCESS'
export const SETUP_ERROR = 'users/SETUP_ERROR'
export const UPDATE_SUCCESS = 'users/UPDATE_SUCCESS'
